#!/usr/bin/env node

const WebTorrent = require('webtorrent')
const client = new WebTorrent()

client.seed("web3root/", function (torrent) {
  console.log('Seeding magnet:?xt=urn:btih:'+torrent.infoHash);
})
